language: c
compiler: clang
env: CONFIG=release OS=linux ARCH=32
before_install: sudo apt-get install gcc-multilib valgrind
branches:
    except: ir
script: >
        make --keep-going print all &&
        make --keep-going print-tests tests
