#include "inc/options.h"

using "inc/options.h";

/*This file gets [re]generated by makedefaults.sh, called by the makefile.
  It is important that each enum constant definition ends in a comma.*/

enum {
    defaultOS = osLinux,
    defaultWordsize = 4,
};
